apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: locust

resources:
  - namespace.yaml
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: locust-master
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: BASE_URL
            value: "http://k3d-shelfware-app-serverlb"
          - name: TARGET_ENV
            value: "prod"
          - name: HOST_HEADER
            value: "shelfware.local"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: locust-worker
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: BASE_URL
            value: "http://k3d-shelfware-app-serverlb"
          - name: TARGET_ENV
            value: "prod"
          - name: HOST_HEADER
            value: "shelfware.local"