apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: locust

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: locust-master
      spec:
        template:
          spec:
            containers:
            - name: locust
              env:
              - name: BASE_URL
                value: "http://k3d-shelfware-app-serverlb"
              - name: TARGET_ENV
                value: "prod"
              - name: HOST_HEADER
                value: "shelfware.local"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: locust-worker
      spec:
        template:
          spec:
            containers:
            - name: locust
              env:
              - name: BASE_URL
                value: "http://k3d-shelfware-app-serverlb"
              - name: TARGET_ENV
                value: "prod"
              - name: HOST_HEADER
                value: "shelfware.local"