apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - crd_alertmanager.yaml
  - crd_prometheus.yaml
  - crd_prometheusrule.yaml
  - crd_servicemonitor.yaml
  - crd_podmonitor.yaml
  - crd_probe.yaml
  - crd_scrapeconfig.yaml
  - crd_thanos.yaml
  - prometheus-operator.yaml

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: replace
        path: /metadata/annotations
        value: {}

  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: replace
        path: /metadata/annotations
        value: {}

  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch: |-
      - op: replace
        path: /metadata/annotations
        value: {}

  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: replace
        path: /metadata/annotations
        value: {}
