apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - crd_alertmanager.yaml
  - crd_prometheus.yaml
  - crd_prometheusrule.yaml
  - crd_servicemonitor.yaml
  - crd_podmonitor.yaml
  - crd_probe.yaml
  - crd_scrapeconfig.yaml
  - crd_thanos.yaml
  - prometheus-operator.yaml

# Add sync-wave annotations to each CRD file
patches:
  - target:
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: probes.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
  - target:
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-10"
