apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - crd_prometheus.yaml
  - crd_prometheusrule.yaml
  - crd_servicemonitor.yaml
  - prometheus-operator.yaml
