apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-shelfware

resources:
- ../../base
- namespace.yaml
- hpa.yaml

patches:
- target:
    kind: ConfigMap
    name: backend-config
  patch: |-
    - op: replace
      path: /data/CORS_ORIGIN
      value: "http://shelfware.local"

- target:
    kind: HTTPRoute
    name: httproute
  patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: "shelfware.local"
labels:
- pairs:
    environment: prod