apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-shelfware

resources:
- ../../base
- namespace.yaml
- ingress.yaml
- keda-scaledobject.yaml

patches:
- patch: |-
    - op: replace
      path: /data/CORS_ORIGIN
      value: "http://shelfware.local"
  target:
    kind: ConfigMap
    name: backend-config
labels:
- pairs:
    environment: prod
images:
- name: ghcr.io/pxl-systems-expert/shelfware-backend
  newName: ghcr.io/demirevren/shelfware-backend
  newTag: PRODv1.0
- name: ghcr.io/pxl-systems-expert/shelfware-frontend
  newName: ghcr.io/demirevren/shelfware-frontend
  newTag: PRODv1.0
