apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # ArgoCD namespace
  - namespace.yaml
  
  # Gateway API CRDs (moet eerst!)
  - gateway-api-crds.yaml

  # ArgoCD installation
  - install.yaml

